### ISSUE TITLE
API Expansion

### ISSUE THREAD

**Issue by SirPopes** [swordmaster2k/rpgwizard#10]
DrawLine, SetPixel, and, if possible, GetPixel.
A way to check the state of an asset would also be nice. I can't find anything related to this other than the OnProgress parameter of [Crafty.load](http://craftyjs.com/api/Crafty-load.html).

Drawcircle (and fillcircle) function. As well as a drawRect (we have fill but not the other).

**Comment by swordmaster2k** [comment]
Added the following RPGCode functions for:

- drawCircle
- fillCircle
- drawRect
- drawLine
- getPixel
- setPixel
- isAssetLoaded (will give you true/false)

@SirPopes, that about covers everything you need right?
