### ISSUE TITLE
JSON files, enemy saving

### ISSUE THREAD

**Issue by SirPopes** [swordmaster2k/rpgwizard#17]
Saving enemy files throws an error. "Error saving file" is all I get as feedback.

.JSON files can't be opened in the editor.

Not sure about this one:
loadJSON and saveJSON could use optional callback variables. They are required to have one atm.
The success callback seems to trigger multiple times. I don't understand the internals of them so *shrugs*

**Comment by swordmaster2k** [comment]
Confirmed that this is an issue, will look to patch the current download.

**Comment by swordmaster2k** [comment]
Fixed, and available in latest download of 1.4.
