### ISSUE TITLE
Will there be a browser editor

### ISSUE THREAD

**Issue by ghost** [swordmaster2k/rpgwizard#36]
Will there be a browser based editor where we can edit from a browser?

**Comment by swordmaster2k** [comment]
Are you thinking about something like ([bitsy](https://ledoux.itch.io/bitsy))? Where you can create your entire game through a browser?

Any particular reason that you are looking for this functionality? Are you running a platform other than windows?

**Comment by ghost** [comment]
> Are you thinking about something like ([bitsy](https://ledoux.itch.io/bitsy))? Where you can create your entire game through a browser?
> 
> Any particular reason that you are looking for this functionality? Are you running a platform other than windows?

Yes, But just asking :smile:

**Comment by swordmaster2k** [comment]
No worries :)

At the minute I don't have any plans for a browser editor. The current one is written in Java SWING which would be difficult to port directly to a browser. 

For RPGWizard 2 I am thinking about a hybrid desktop editor using ElectronJS, which could potentially make it possible to edit your games in a browser. I don't expect to start that until 2020 though :P

**Comment by ghost** [comment]
Oh,
If only java swing was supported in android, it would've been easy to port it to android.
You could publish it to earn some cash, those simple game makers in play store that don't support exporting of games let alone custom assets are having 100k downloads.

Guess I'll wait for 2020 then :+1:

**Comment by swordmaster2k** [comment]
So you are actually looking for an RPG editor to make your games on Android itself? XD

Can you provide an example of one that is already on the play store for future reference?

**Comment by ghost** [comment]
Two examples are:
this one has 10k downloads
https://play.google.com/store/apps/details?id=nebiogames.gmkr

And this one has 100k
https://play.google.com/store/apps/details?id=game.maker.pro

Both are simple level editors and both have 100k downloads.

If you could make it to android you could easily make a famous game maker.

If only java swing was supported on android, haha
