### ISSUE TITLE
Excuse me, can this game engine make turn based RPG?

### ISSUE THREAD

**Issue by txj-mssl** [swordmaster2k/rpgwizard#74]

**Comment by txj-mssl** [comment]
I am looking for a game engine to replace rpgmv

**Comment by txj-mssl** [comment]
I've checked it and can make turn games.

**Comment by swordmaster2k** [comment]
Hi @txj-mssl, sorry I was meant to reply to this earlier. Yes this engine is geared towards making RPG style games.

It is similar to RPG Maker, I recommend checking out the Wiki section, there is a link to the "Getting Started" YouTube series there:

https://github.com/swordmaster2k/rpgwizard/wiki
